version: "3"
services:
  gateway:
    image: ghcr.io/defguard/gateway:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      # load variables from .env file
      - DEFGUARD_GRPC_URL
      - DEFGUARD_TOKEN
      - DEFGUARD_STATS_PERIOD
      - RUST_LOG=debug
      # SSL setup guide: https://defguard.gitbook.io/defguard/features/setting-up-your-instance/docker-compose#ssl-setup
      # - DEFGUARD_GRPC_CA: /ssl/defguard-ca.pem
    ports:
      # wireguard endpoint
      - "50051:50051/udp"
    #volumes:
      # SSL setup guide: https://defguard.gitbook.io/defguard/features/setting-up-your-instance/docker-compose#ssl-setup
      #- ./.volumes/ssl:/ssl
    cap_add:
      - NET_ADMIN
