apiVersion: v1
kind: Service
metadata:
  name: {{ include "defguard.fullname" . }}-web
  labels:
    {{- include "defguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "defguard.selectorLabels" . | nindent 4 }}
