{{- if .Values.enrollment.enabled -}}
{{- if .Values.enrollment.ingress.enabled -}}
{{- $fullName := include "enrollment.name" . -}}
{{- if and .Values.enrollment.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.enrollment.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.enrollment.ingress.annotations "kubernetes.io/ingress.class" .Values.enrollment.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "defguard.labels" . | nindent 4 }}
  {{- with .Values.enrollment.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.enrollment.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.enrollment.ingress.className }}
  {{- end }}
  {{- if .Values.enrollment.ingress.tls }}
  tls:
    {{- range .Values.enrollment.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.enrollment.ingress.hosts.web | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-web
                port:
                  number: {{ .Values.enrollment.service.ports.http }}
              {{- else }}
              serviceName: {{ $fullName }}-web
              servicePort: {{ .Values.enrollment.service.ports.http }}
              {{- end }}
{{- end }}
{{- end }}
