apiVersion: v1
kind: Secret
metadata:
  name: {{ include "defguard.fullname" . }}-license
  labels:
    {{- include "defguard.labels" . | nindent 4 }}
type: Opaque
data:
  license: {{ .Values.license | b64enc | quote }}
