{{- $openIdKey := (genPrivateKey "rsa") | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.openIdKey) }}
{{- if $secret }}
{{- $openIdKey = index $secret.data "openid-key" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openIdKey }}
  labels:
    {{- include "defguard.labels" . | nindent 4 }}
type: Opaque
data:
  openid-key: {{ $openIdKey }}
