{{ if .Values.postgresql.enabled }}
{{- $secretName := .Values.postgresql.auth.existingSecret | default (printf "%s-postgresql" .Release.Name) }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}

{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "defguard.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  password: {{ randAlpha 16 | b64enc | quote }}
  postgres-password: {{ randAlpha 16 | b64enc | quote }}
{{- end }}
{{- end }}
