apiVersion: v2
name: defguard
description: Defguard is an open-source enterprise WireGuard VPN with MFA and SSO.
icon: https://defguard.net/favicon/favicon-512x512.png

type: application
version: 1.6.0
appVersion: 1.6.6

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 18.6.2
    repository: https://charts.bitnami.com/bitnami
  - name: defguard-proxy
    condition: defguard-proxy.enabled
    version: 1.6.3
    repository: https://defguard.github.io/deployment
    # repository: "file://../defguard-proxy"
  - name: defguard-gateway
    condition: defguard-gateway.enabled
    version: 1.6.5
    repository: https://defguard.github.io/deployment
    # repository: "file://../defguard-gateway"
