resources:
  - core-service.yaml
  - core-deployment.yaml
  - core-ingress.yaml
  - db-deployment.yaml
  - db-service.yaml
  - db-persistentvolumeclaim.yaml
configMapGenerator:
  - name: web
    envs:
      - config.env
