services:
  core:
    image: ghcr.io/defguard/defguard:dev
    environment:
      DEFGUARD_COOKIE_INSECURE: "true"
      DEFGUARD_SECRET_KEY: defguard-secret-key-defguard-secret-key-defguard-secret-key-defguard-secret-key
      DEFGUARD_AUTH_SECRET: defguard-auth-secret
      DEFGUARD_GATEWAY_SECRET: defguard-gateway-secret
      DEFGUARD_YUBIBRIDGE_SECRET: defguard-yubibridge-secret
      DEFGUARD_DB_HOST: db
      DEFGUARD_DB_PORT: 5432
      DEFGUARD_DB_USER: defguard
      DEFGUARD_DB_PASSWORD: defguard
      DEFGUARD_DB_NAME: defguard
      DEFGUARD_ADOPT_EDGE: "edge1:50051"
      DEFGUARD_ADOPT_GATEWAY: "gateway1:50066"
    depends_on:
      - db
      - gateway1
      - edge1
    ports:
      - "8000:8000"

  edge1:
    image: ghcr.io/defguard/defguard-proxy:2.0.0-alpha2
    volumes:
      - ./.volumes/certs2.0/edge1:/etc/defguard/certs
    ports:
      - "8080:8080"

  gateway1:
    image: ghcr.io/defguard/gateway:2.0.0-alpha2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./.volumes/certs2.0/gateway1:/etc/defguard/certs
    ports:
      - "51820:51820/udp"
    environment:
      DEFGUARD_STATS_PERIOD: 10
      HEALTH_PORT: 55003

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: defguard
      POSTGRES_USER: defguard
      POSTGRES_PASSWORD: defguard
    volumes:
      - ./.volumes/db2.0:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"   # web UI
      - "1025:1025"   # SMTP

  openldap:
    image: bitnamilegacy/openldap:2.6
    user: root
    restart: unless-stopped
    environment:
      LDAP_ADMIN_PASSWORD: "pass123"
    ports:
      - "389:1389"
    volumes:
      - ./ldap/entrypoint:/docker-entrypoint-initdb.d:ro
      - ./ldap/init.ldif:/ldifs/init.ldif:ro
      - ./ldap/custom.ldif:/schema/custom.ldif:ro
      - ./volumes/openldap:/bitnami/openldap

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    restart: unless-stopped
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'host': 'openldap', 'port': 1389}]}]}]"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"  
