services:
  core:
    image: ghcr.io/defguard/defguard:dev
    environment:
      DEFGUARD_COOKIE_INSECURE: "true"
      DEFGUARD_SECRET_KEY: defguard-secret-key-defguard-secret-key-defguard-secret-key-defguard-secret-key
      DEFGUARD_AUTH_SECRET: defguard-auth-secret
      DEFGUARD_GATEWAY_SECRET: defguard-gateway-secret
      DEFGUARD_YUBIBRIDGE_SECRET: defguard-yubibridge-secret
      DEFGUARD_DB_HOST: db
      DEFGUARD_DB_PORT: 5432
      DEFGUARD_DB_USER: defguard
      DEFGUARD_DB_PASSWORD: defguard
      DEFGUARD_DB_NAME: defguard
      DEFGUARD_ADOPT_EDGE: "edge1:50051"
      DEFGUARD_ADOPT_GATEWAY: "gateway1:50066"
    depends_on:
      - db
      - gateway1
      - edge1
    ports:
      - "8000:8000"

  edge1:
    image: ghcr.io/defguard/defguard-proxy:dev
    volumes:
      - ./.volumes/certs2.0/edge1:/etc/defguard/certs
    ports:
      - "8080:8080"

  gateway1:
    image: ghcr.io/defguard/gateway:dev
    cap_add:
      - NET_ADMIN
    volumes:
      - ./.volumes/certs2.0/gateway1:/etc/defguard/certs
    ports:
      - "51820:51820/udp"
    environment:
      DEFGUARD_STATS_PERIOD: 10
      HEALTH_PORT: 55003

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: defguard
      POSTGRES_USER: defguard
      POSTGRES_PASSWORD: defguard
    volumes:
      - ./.volumes/db2.0:/var/lib/postgresql
    ports:
      - "5432:5432"
