apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "defguard-proxy.fullname" . }}-config
  labels:
    {{- include "defguard-proxy.labels" . | nindent 4 }}
data:
  DEFGUARD_PROXY_HTTP_PORT: {{ .Values.service.web.port | quote }}
  DEFGUARD_PROXY_GRPC_PORT: {{ .Values.service.grpc.port | quote }}
  DEFGUARD_PROXY_URL: {{ .Values.publicUrl | quote }}
