#!/bin/bash
# Flattens the profile-gated compose template into a single, self-contained
# /opt/stacks/defguard/docker-compose.yml on first boot, then removes the
# cloud-init mode-selection flag files so the stack directory stays clean.
# If docker-compose.yml already exists, this script does nothing.
set -euo pipefail

STACK_DIR="${DEFGUARD_STACK_DIR:-/opt/stacks/defguard}"
INIT_DIR="${DEFGUARD_INIT_DIR:-$STACK_DIR/init}"
TEMPLATE="$INIT_DIR/docker-compose.template.yaml"
COMPOSE_FILE="$STACK_DIR/docker-compose.yml"
PROFILES_FILE="$STACK_DIR/active-profiles"
ENABLE_DOCKER_MGMT_FILE="$STACK_DIR/enable-docker-management"

if [ -f "$COMPOSE_FILE" ]; then
  echo "DefGuard: docker-compose.yml already exists, skipping generation."
  exit 0
fi

# shellcheck source=lib.sh
source "$INIT_DIR/lib.sh"

mapfile -t _profiles < <(resolve_profiles "$STACK_DIR")

FULL_STACK=false
if is_full_stack "${_profiles[@]}"; then
  FULL_STACK=true
fi

_profile_args=()
for p in "${_profiles[@]}"; do _profile_args+=(--profile "$p"); done

# `docker compose config --profile X` (repeatable) filters the emitted service
# list to active-profile + unprofiled services, but surviving services keep
# their `profiles:` key - which would make them invisible to a future plain
# `docker compose up -d` with no COMPOSE_PROFILES set. jq strips that key and
# injects the conditional depends_on/port tweaks; the result is then piped
# back through `docker compose config` (stdin) to render real YAML rather
# than leaving the file as JSON-flavored-as-YAML.
TMP_COMPOSE_FILE="$COMPOSE_FILE.tmp"
trap 'rm -f "$TMP_COMPOSE_FILE"' EXIT
{
  echo "# Generated by defguard OVA first-boot init on $(date -u +%FT%TZ)."
  echo "# Selected profiles: ${_profiles[*]}"
  docker compose -f "$TEMPLATE" -p defguard --project-directory "$STACK_DIR" --env-file "$STACK_DIR/.env" "${_profile_args[@]}" \
    config --format json \
    | jq --argjson full "$FULL_STACK" '
        del(.services[].profiles) | del(.name)
        | if $full then
            .services.core.depends_on = ["db", "edge", "gateway"]
          else
            (.services.edge // empty) |= (.ports += ["50051:50051"])
          end
      ' \
    | docker compose -f - -p defguard --project-directory "$STACK_DIR" config
} > "$TMP_COMPOSE_FILE"
mv "$TMP_COMPOSE_FILE" "$COMPOSE_FILE"

rm -f "$PROFILES_FILE" "$ENABLE_DOCKER_MGMT_FILE"
echo "DefGuard: generated $COMPOSE_FILE for profiles: ${_profiles[*]}"
