#!/bin/bash
# Flattens the profile-gated compose template into a single, self-contained
# /opt/stacks/defguard/docker-compose.yml on first boot, then removes the
# cloud-init mode-selection flag files so the stack directory stays clean.
# If docker-compose.yml already exists, this script does nothing.
set -euo pipefail

STACK_DIR="${DEFGUARD_STACK_DIR:-/opt/stacks/defguard}"
INIT_DIR="${DEFGUARD_INIT_DIR:-$STACK_DIR/init}"
TEMPLATE="$INIT_DIR/docker-compose.template.yaml"
COMPOSE_FILE="$STACK_DIR/docker-compose.yml"
PROFILES_FILE="$STACK_DIR/active-profiles"
ENABLE_DOCKER_MGMT_FILE="$STACK_DIR/enable-docker-management"
DEPLOYMENT_MODE_FILE="$INIT_DIR/.deployment-mode"

if [ -f "$COMPOSE_FILE" ]; then
  echo "DefGuard: docker-compose.yml already exists, skipping generation."
  exit 0
fi

# shellcheck source=lib.sh
source "$INIT_DIR/lib.sh"

mapfile -t _profiles < <(resolve_profiles "$STACK_DIR")

PERSISTED_MODE="$(deployment_mode "$INIT_DIR")" \
  || { echo "DefGuard: invalid deployment mode in $DEPLOYMENT_MODE_FILE" >&2; exit 1; }
if [ -n "${DEFGUARD_DEPLOYMENT_MODE:-}" ]; then
  MODE="$DEFGUARD_DEPLOYMENT_MODE"
elif [ "$PERSISTED_MODE" = segmented ]; then
  # A legacy standalone deployment may legitimately select all three
  # profiles; retain its segmented network semantics across regeneration.
  MODE=segmented
elif [ -f "$PROFILES_FILE" ]; then
  # An explicit mode-selection file is a fresh operator/cloud-init input and
  # takes precedence over a marker left by an earlier generated file.
  MODE=auto
else
  MODE="$PERSISTED_MODE"
fi
case "$MODE" in
  auto|full|segmented) ;;
  *) echo "DefGuard: invalid deployment mode '$MODE'" >&2; exit 1 ;;
esac
FULL_STACK=false
case "$MODE" in
  full) FULL_STACK=true ;;
  segmented) ;;
  auto)
    if is_full_stack "${_profiles[@]}"; then
      FULL_STACK=true
    fi
    ;;
esac

_profile_args=()
for p in "${_profiles[@]}"; do _profile_args+=(--profile "$p"); done

# `docker compose config --profile X` (repeatable) filters the emitted service
# list to active-profile + unprofiled services, but surviving services keep
# their `profiles:` key - which would make them invisible to a future plain
# `docker compose up -d` with no COMPOSE_PROFILES set. jq strips that key and
# injects the conditional depends_on/port tweaks; the result is then piped
# back through `docker compose config` (stdin) to render real YAML rather
# than leaving the file as JSON-flavored-as-YAML. Keep paths unexpanded because
# upgrades generate this file in a temporary staging directory before copying
# it into the permanent stack directory; running from STACK_DIR lets Compose
# still validate the relative .env file.
TMP_COMPOSE_FILE="$COMPOSE_FILE.tmp"
trap 'rm -f "$TMP_COMPOSE_FILE" "$DEPLOYMENT_MODE_FILE.tmp"' EXIT
{
  echo "# Generated by defguard OVA first-boot init on $(date -u +%FT%TZ)."
  echo "# Selected profiles: ${_profiles[*]}"
  (cd "$STACK_DIR" && docker compose -f "$TEMPLATE" -p defguard --project-directory "$STACK_DIR" --env-file "$STACK_DIR/.env" "${_profile_args[@]}" \
    config --no-path-resolution --format json) \
    | jq --argjson full "$FULL_STACK" '
        del(.services[].profiles) | del(.name)
        | if $full then
            .services.core.depends_on = ["db", "edge", "gateway"]
          else
            (.services.edge // empty) |= (.ports += ["50051:50051"])
          end
      ' \
    | (cd "$STACK_DIR" && docker compose -f - -p defguard --project-directory "$STACK_DIR" config --no-path-resolution)
} > "$TMP_COMPOSE_FILE"

sed -i.bak \
  -e "s/__DEFGUARD_CORE_TAG__/\${DEFGUARD_CORE_TAG}/" \
  -e "s/__DEFGUARD_PROXY_TAG__/\${DEFGUARD_PROXY_TAG}/" \
  -e "s/__DEFGUARD_GATEWAY_TAG__/\${DEFGUARD_GATEWAY_TAG}/" \
  "$TMP_COMPOSE_FILE" && rm -f "$TMP_COMPOSE_FILE.bak"

mv "$TMP_COMPOSE_FILE" "$COMPOSE_FILE"

if [ "$FULL_STACK" = true ]; then
  printf '%s\n' full > "$DEPLOYMENT_MODE_FILE.tmp"
else
  printf '%s\n' segmented > "$DEPLOYMENT_MODE_FILE.tmp"
fi
mv "$DEPLOYMENT_MODE_FILE.tmp" "$DEPLOYMENT_MODE_FILE"

# The generated file carries no profiles: keys, so record the selection for
# later regeneration (see /opt/defguard/dg-ctl upgrade).
mkdir -p "$INIT_DIR"
printf '%s\n' "${_profiles[@]}" > "$INIT_DIR/.applied-profiles"

rm -f "$PROFILES_FILE" "$ENABLE_DOCKER_MGMT_FILE"
echo "DefGuard: generated $COMPOSE_FILE for profiles: ${_profiles[*]}"
