worker_processes auto;

error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

stream {
  log_format udp '$remote_addr:$remote_port [$time_local] '
                 '$protocol $status bytes_sent=$bytes_sent bytes_received=$bytes_received '
                 'session_time=$session_time upstream=$upstream_addr';

  access_log /dev/stdout udp;

  upstream defguard_gateways_udp {
    server gateway1:50051 max_fails=1 fail_timeout=1s;
    server gateway2:50051 max_fails=1 fail_timeout=1s;
  }

  server {
    listen 50051 udp reuseport;
    proxy_pass defguard_gateways_udp;
    proxy_connect_timeout 1s;
    proxy_timeout 60s;
  }
}
