apiVersion: v2
name: defguard-proxy
description: Defguard Edge is a public-facing proxy for Defguard Core.
icon: https://defguard.net/favicon/favicon-512x512.png

type: application
version: 2.0.0
appVersion: 2.0.0
