{
 "title": "Defguard - Processes",
 "tags": [
  "defguard",
  "processes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total[5m])",
     "legendFormat": "{{groupname}} / {{instance}}"
    }
   ]
  },
  {
   "title": "Process resident memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{ memtype=\"resident\"}",
     "legendFormat": "{{groupname}} / {{instance}}"
    }
   ]
  },
  {
   "title": "Process states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_states",
     "legendFormat": "{{groupname}} {{state}} / {{instance}}"
    }
   ]
  }
 ]
}