affinity: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
cookie:
  domain: ""
  insecure: false
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/defguard/defguard
  tag: ""
imagePullSecrets: []
ingress:
  grpc:
    annotations: {}
    className: ""
    enabled: true
    host: defguard-grpc.local
    tls: false
  web:
    annotations: {}
    className: ""
    enabled: true
    host: defguard.local
    tls: false
existingJwtSecret: ""
ldap:
  admin_group: ""
  bind_password: ""
  bind_username: ""
  enabled: false
  group_search_base: ""
  url: ""
  user_search_base: ""
nameOverride: ""
nodeSelector: {}
existingOpenIdSecret: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# sub-chart bitnami/postgresql
postgresql:
  enabled: true
  host: "" # set if using external postgresql ~ enabled: false
  port: 5432
  auth:
    database: defguard
    existingSecret: postgres-password
    existingSecretPasswordKey: "" # set if using external postgresql ~ enabled: false
    username: defguard
proxyUrl: ""
publicUrl: "http://defguard.local"
replicaCount: 1
resources: {}
securityContext: {}
service:
  ports:
    grpc: 50055
    http: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
tolerations: []
# sub-chart defguard-proxy
defguard-proxy:
  enabled: false
  publicUrl: "http://enrollment.local"
  ingress:
    grpc:
      host: defguard-proxy-grpc.local
    web:
      host: enrollment.local
additionalEnvFromConfigMap: ""
