affinity: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/defguard/defguard
  tag: ""
imagePullSecrets: []
ingress:
  annotations: {}
  className: ""
  enabled: true
  hosts:
    grpc: defguard-grpc.local
    web: defguard.local
  tls: []
jwtSecret: jwt-secrets
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# sub-chart bitnami/postgresql
postgresql:
  auth:
    database: defguard
    existingSecret: postgres-password
    username: defguard
publicUrl: "http://defguard.local"
replicaCount: 1
resources: {}
securityContext: {}
service:
  ports:
    grpc: 50055
    http: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
tolerations: []
license: ""
enrollment:
  enabled: false
  nameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/defguard/defguard-proxy
    tag: "latest"
  imagePullSecrets: [ ]
  ingress:
    annotations: { }
    className: ""
    enabled: true
    hosts:
      web: enrollment.local
    tls: [ ]
  nodeSelector: { }
  podAnnotations: { }
  podLabels: { }
  podSecurityContext: { }
  publicUrl: "http://enrollment.local"
  replicaCount: 1
  resources: { }
  securityContext: { }
  service:
    ports:
      http: 8080
    type: ClusterIP
  serviceAccount:
    annotations: { }
    create: true
  tolerations: [ ]

