apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "defguard-gateway.fullname" . }}-config
  labels:
    {{- include "defguard-gateway.labels" . | nindent 4 }}
data:
  DEFGUARD_USERSPACE: {{ .Values.userspace | quote }}
  DEFGUARD_GRPC_URL: {{ .Values.grpcUrl | quote }}
  DEFGUARD_STATS_PERIOD: {{ .Values.statsPeriod | quote }}
  DEFGUARD_LOG_LEVEL: {{ .Values.logLevel | quote }}
