apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defguard-gateway.fullname" . }}
  labels:
    {{- include "defguard-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "defguard-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "defguard-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "defguard-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: {{ include "defguard-gateway.fullname" . }}-config
            {{- if .Values.additionalEnvFromConfigMap }}
            - configMapRef:
                name: {{ .Values.additionalEnvFromConfigMap }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.ports.grpc }}
              protocol: UDP
            - name: wireguard # make it explicit
              containerPort: {{ .Values.service.ports.wireguard }}
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.token }}
          env:
            - name: DEFGUARD_TOKEN
              value: {{ .Values.token }}
          {{- else if .Values.existingTokenSecret }}
          env:
            - name: DEFGUARD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingTokenSecret }}
                  key: {{ .Values.existingTokenSecretKey }}
          {{- end }}
        # used to keep nlb happy to do health checks at port 80.
        # Alternatively, we could add this command to the Dockerfile
        - name: tcp-healthcheck
          image: alpine/socat:latest
          imagePullPolicy: IfNotPresent
          command:
            - socat
            - "TCP-LISTEN:80,reuseaddr,fork"
            - "SYSTEM:true"
          ports:
            - name: health
              containerPort: 80
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
