apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "defguard-gateway.labels" . | nindent 4 }}
  name: {{ include "defguard-gateway.fullname" . }}-grpc-headless
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      protocol: TCP
      targetPort: grpc
  selector:
    {{- include "defguard-gateway.selectorLabels" . | nindent 4 }}
