apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- with .Values.service.grpc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "defguard-gateway.fullname" . }}-grpc
  labels:
    {{- include "defguard-gateway.labels" . | nindent 4 }}
    {{- with .Values.service.grpc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.grpc.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: UDP
      name: grpc
  selector:
    {{- include "defguard-gateway.selectorLabels" . | nindent 4 }}
