{{ if eq .Values.cloudProvider "aws" }}

apiVersion: v1
kind: Service
metadata:
  # service creates an aws NLB which exposes
  annotations:
    # Force the NLB’s health check to use TCP:443 (or 80, or any open TCP port)
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  name: {{ include "defguard-gateway.fullname" . }}-wireguard
  labels:
    {{- include "defguard-gateway.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.ports.wireguard }}
      targetPort: wireguard
      protocol: UDP
      name: wireguard
  selector:
    {{- include "defguard-gateway.selectorLabels" . | nindent 4 }}

{{ end }}